"""CORRECTED break-even: per-cell cost uses the production HUB-BUNDLED express
(dd_cost + attributed _hub_express_day_ml), not the per-PLZ unbundled cost_3d.

The hub-bundled express is a per-(hub,day) cost; it is attributed back to each
contributing PLZ proportionally to that PLZ's express demand raw_express[pi,d].
This reproduces the production grid's saving exactly (verified) while giving a
per-cell breakdown for the break-even / region analysis.

Overwrites tab_breakeven_per_cell.csv (now bundled) + tab_breakeven_share_by_raumtyp.csv
and regenerates fig_BE1, fig_BE2. (BE3/BE4 are at share=100% -> no express -> unchanged.
BE5-BE8 are regenerated by re-running paper_final_breakeven_readoff.py on the new CSV.)

DEPRECATED (2026-08 revision). Stale entry point: it recomputes totals
WITHOUT the pool term and predates the universal tour rule, the two cost
lenses and the operator polish, so its numbers are not comparable with the
current results. Use scripts/revision/61_grid_run_v2.py for the grid and
scripts/revision/70_figs_tables_v2.py for figures and tables.
"""
from __future__ import annotations
import importlib.util, pickle, sys, warnings
from pathlib import Path

warnings.filterwarnings("ignore")

# --- DEPRECATED ENTRY POINT (2026-08 revision) -----------------------------
import warnings as _deprecation_warnings

_deprecation_warnings.warn(
    "paper_final_breakeven_bundled.py is a STALE entry point: it recomputes totals WITHOUT the pool "
    "term and predates the universal tour rule, the two cost lenses and the "
    "operator polish. Its numbers are NOT comparable with the 2026-08 "
    "revision. Use scripts/revision/61_grid_run_v2.py for the grid and "
    "scripts/revision/70_figs_tables_v2.py for figures and tables.",
    DeprecationWarning,
    stacklevel=2,
)
# ---------------------------------------------------------------------------

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib import rcParams

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))
OPT = ROOT / "results" / "paper_final_2026_05_30" / "05_optimization"
OUT = ROOT / "results" / "paper_final_2026_05_30" / "09_region_analysis"
rcParams.update({
    "font.family": "serif", "font.size": 12,
    "axes.labelsize": 13, "axes.titlesize": 13.5,
    "savefig.bbox": "tight", "savefig.dpi": 300, "pdf.fonttype": 42,
    "axes.spines.top": False, "axes.spines.right": False,
})
RT_COLOR = {"rural": "#2a9d8f", "suburban": "#e9c46a", "urban": "#e76f51"}
RT_ORDER = ["urban", "suburban", "rural"]
P_BE = 0.0


def load_module():
    spec = importlib.util.spec_from_file_location(
        "orch_bal", ROOT / "scripts" / "overnight_orchestrator_balanced.py")
    mod = importlib.util.module_from_spec(spec); spec.loader.exec_module(mod)
    return mod


def breakeven_share(sh, sv, thr):
    sv = np.asarray(sv, float)
    if np.nanmax(sv) < thr:
        return np.nan
    for i in range(1, len(sh)):
        if sv[i] >= thr and sv[i - 1] < thr:
            t = (thr - sv[i - 1]) / (sv[i] - sv[i - 1]) if sv[i] != sv[i - 1] else 0.0
            return sh[i - 1] + t * (sh[i] - sh[i - 1])
        if sv[i] >= thr and sv[i - 1] >= thr:
            return sh[i - 1]
    return sh[-1]


def main():
    from batch_delivery.optimization.core import _hub_express_day_ml
    mod = load_module()
    N_DAYS = mod.N_DAYS
    print("Loading checkpoints + model...")
    chk = pickle.load(open(ROOT / "results/checkpoints/01_demand.pkl", "rb"))
    chk4 = pickle.load(open(ROOT / "results/checkpoints/04_optim_prep.pkl", "rb"))
    optim_data = chk4["optimization_data"]
    model = mod.load_model()
    ml_prep = mod.build_ml_prep(chk["provider_data"])
    schedules = mod.enumerate_schedules()
    daily_si = next(i for i, s in enumerate(schedules) if len(s) == N_DAYS)

    ch = pd.read_csv(OPT / "tab_chosen_schedules_full.csv")
    ch["plz"] = ch.plz.astype(str).str.zfill(5)
    SHARE_GRID = sorted(ch.share_willing.unique())
    P_GRID = [0.0, 0.4]
    OP_P, OP_SHARE = 0.4, 1.0   # operating point for spatial cuts (BE3/BE4)

    recs = []
    for share in SHARE_GRID:
        fs_b2c_v, fs_b2b_v = mod.fs_b2c(share), mod.fs_b2b(share)
        prov_mat = {}
        for prov in mod.PROVIDERS:
            if prov not in optim_data or prov not in ml_prep:
                continue
            odata = optim_data[prov]; prep = ml_prep[prov]
            mat = mod.build_cost_matrices_ml(
                odata["plz_keys"], odata["plz_data"], schedules, model, prov,
                prep["plz_day_coords"], prep["hub_coords_by_plz"],
                fast_share_b2c=fs_b2c_v, fast_share_b2b=fs_b2b_v,
            )
            prov_mat[prov] = (odata, mat)
        for P in P_GRID:
            for prov, (odata, mat) in prov_mat.items():
                plz_keys = odata["plz_keys"]; hub_plz_list = odata["hub_plz_list"]
                sa = mat["sched_active"]; dd_cost_mx = mat["dd_cost_mx"]
                raw_express = mat["raw_express"]
                sub = ch[(ch.penalty == P) & (ch.share_willing == share) & (ch.provider == prov)]
                idx_by = {r.plz: int(r.schedule_idx_balanced) for r in sub.itertuples()}
                chosen = np.array([idx_by.get(str(pc).zfill(5), daily_si) for pc in plz_keys])
                n = len(plz_keys)
                # per-cell delivery-day cost + attributed hub-bundled express
                cell_cost = dd_cost_mx[np.arange(n), chosen].astype(float).copy()
                cell_base = dd_cost_mx[:, daily_si].astype(float)
                cache = {}
                for hi, h_ps in enumerate(hub_plz_list):
                    if len(h_ps) == 0:
                        continue
                    for d in range(N_DAYS):
                        hub_e = _hub_express_day_ml(
                            hi, d, chosen, hub_plz_list, schedules,
                            raw_express, mat["expr_stops"], mat, cache)
                        if hub_e <= 0:
                            continue
                        nd = (~sa[chosen[h_ps], d]) & (raw_express[h_ps, d] > 0)
                        w = raw_express[h_ps, d] * nd
                        wsum = w.sum()
                        if wsum > 0:
                            cell_cost[h_ps] += hub_e * (w / wsum)
                for pi, pc in enumerate(plz_keys):
                    recs.append({"provider": prov, "plz": str(pc).zfill(5),
                                 "penalty": P, "share_willing": share,
                                 "total_eur": cell_cost[pi], "baseline_eur": cell_base[pi]})
        print(f"  share={share:.1f} done")

    cell = pd.DataFrame(recs)
    cell["saving_pct"] = 100 * (cell.baseline_eur - cell.total_eur) / cell.baseline_eur.clip(lower=1)
    feat = pd.read_csv(OUT / "tab_breakeven_per_cell.csv")[
        ["provider", "plz", "area_km2", "hub_dist_km", "n_stops", "weekly_parcels", "raumtyp_3"]]
    feat["plz"] = feat.plz.astype(str).str.zfill(5)
    feat = feat.drop_duplicates(["provider", "plz"])
    cell = cell.merge(feat, on=["provider", "plz"], how="left")
    cell.to_csv(OUT / "tab_breakeven_per_cell.csv", index=False)

    # break-even per cell at P=0
    g0 = cell[cell.penalty == P_BE]
    be = []
    for (prov, pc), g in g0.groupby(["provider", "plz"]):
        g = g.sort_values("share_willing")
        be.append({"raumtyp_3": g.raumtyp_3.iloc[0],
                   "max_saving": float(np.nanmax(g.saving_pct)),
                   "be_pos": breakeven_share(g.share_willing.values, g.saving_pct.values, 0.5),
                   "be_5": breakeven_share(g.share_willing.values, g.saving_pct.values, 5.0)})
    bedf = pd.DataFrame(be)
    summ = []
    for rt in RT_ORDER:
        s = bedf[bedf.raumtyp_3 == rt]
        summ.append({"raumtyp_3": rt, "n_cells": len(s),
                     "pct_ever_profitable": 100 * s.be_pos.notna().mean(),
                     "median_breakeven_share_pos": np.nanmedian(s.be_pos) * 100,
                     "median_breakeven_share_5pct": np.nanmedian(s.be_5) * 100,
                     "median_max_saving": s.max_saving.median()})
    sdf = pd.DataFrame(summ)
    sdf.to_csv(OUT / "tab_breakeven_share_by_raumtyp.csv", index=False)
    print("\nCORRECTED (bundled) break-even by region type:")
    print(sdf.round(1).to_string(index=False))

    # BE1 corrected
    fig, ax = plt.subplots(figsize=(8, 5.5))
    for rt in RT_ORDER:
        s = g0[g0.raumtyp_3 == rt].groupby("share_willing").saving_pct.median()
        ax.plot(s.index * 100, s.values, "o-", color=RT_COLOR[rt], lw=2, ms=5, label=rt)
    ax.axhline(0, color="black", lw=0.9, ls="--")
    ax.set_xlabel("Share willing to wait  [%]"); ax.set_ylabel("Median cell cost saving  [%]")
    ax.set_xlim(-3, 103); ax.grid(alpha=0.25); ax.legend(title="Region type")
    fig.tight_layout()
    fig.savefig(OUT / "fig_BE1_saving_vs_share_by_raumtyp.png")
    fig.savefig(OUT / "fig_BE1_saving_vs_share_by_raumtyp.pdf")
    plt.close(fig); print("  [OK] fig_BE1 (corrected)")

    # BE2 corrected
    fig, ax = plt.subplots(figsize=(8, 5.5))
    data = [bedf[bedf.raumtyp_3 == rt].be_pos.dropna().values * 100 for rt in RT_ORDER]
    bp = ax.boxplot(data, labels=RT_ORDER, patch_artist=True, widths=0.6, showfliers=False)
    for patch, rt in zip(bp["boxes"], RT_ORDER):
        patch.set_facecolor(RT_COLOR[rt]); patch.set_alpha(0.7)
    for med in bp["medians"]:
        med.set_color("black")
    ax.set_ylabel("Break-even willingness share  [%]"); ax.set_xlabel("Region type")
    ax.set_title("Minimum adoption for consolidation to pay off (bundled)")
    ax.grid(axis="y", alpha=0.25)
    fig.tight_layout()
    fig.savefig(OUT / "fig_BE2_breakeven_share_by_raumtyp.png")
    fig.savefig(OUT / "fig_BE2_breakeven_share_by_raumtyp.pdf")
    plt.close(fig); print("  [OK] fig_BE2 (corrected)")

    # BE3 corrected: spatial break-even at operating point (bundled)
    op = cell[(cell.penalty == OP_P) & (cell.share_willing == OP_SHARE)]
    fig, ax = plt.subplots(figsize=(8.5, 6))
    for rt in RT_ORDER:
        s = op[op.raumtyp_3 == rt]
        ax.scatter(s.hub_dist_km, s.saving_pct, s=np.sqrt(s.area_km2) * 12,
                   color=RT_COLOR[rt], alpha=0.65, edgecolor="black", lw=0.4, label=rt)
    ax.axhline(0, color="black", lw=0.9, ls="--")
    ax.set_xlabel("Hub distance  [km]")
    ax.set_ylabel(f"Cell cost saving  [%]   (P={OP_P:g}, share={OP_SHARE:.0%})")
    ax.set_title("Spatial break-even — bubble size ∝ √area")
    ax.grid(alpha=0.25); ax.legend(title="Region type", loc="upper left")
    fig.tight_layout()
    fig.savefig(OUT / "fig_BE3_spatial_breakeven.png")
    fig.savefig(OUT / "fig_BE3_spatial_breakeven.pdf")
    plt.close(fig); print("  [OK] fig_BE3 (corrected)")

    # BE4 corrected: hub_dist x area median-saving heatmap (bundled)
    op = op.copy()
    op["hd_bin"] = pd.cut(op.hub_dist_km, [0, 5, 10, 20, 100], labels=["0-5", "5-10", "10-20", "20+"])
    op["area_bin"] = pd.cut(op.area_km2, [0, 5, 20, 50, 1e4], labels=["<5", "5-20", "20-50", "50+"])
    piv = op.pivot_table(index="area_bin", columns="hd_bin", values="saving_pct", aggfunc="median")
    fig, ax = plt.subplots(figsize=(7.5, 6))
    im = ax.imshow(piv.values, aspect="auto", cmap="RdYlGn", vmin=-5, vmax=25, origin="lower")
    ax.set_xticks(range(len(piv.columns))); ax.set_xticklabels(piv.columns)
    ax.set_yticks(range(len(piv.index))); ax.set_yticklabels(piv.index)
    for i in range(piv.shape[0]):
        for j in range(piv.shape[1]):
            v = piv.values[i, j]
            if not np.isnan(v):
                ax.text(j, i, f"{v:.0f}%", ha="center", va="center", fontsize=11, color="black")
    ax.set_xlabel("Hub distance  [km]"); ax.set_ylabel("PLZ area  [km²]")
    ax.set_title(f"Median saving by hub-distance x area  (P={OP_P:g}, share={OP_SHARE:.0%})")
    plt.colorbar(im, ax=ax, label="Median saving [%]", shrink=0.8)
    fig.tight_layout()
    fig.savefig(OUT / "fig_BE4_hubdist_area_heatmap.png")
    fig.savefig(OUT / "fig_BE4_hubdist_area_heatmap.pdf")
    plt.close(fig); print("  [OK] fig_BE4 (corrected)")
    print("\nDone — corrected per-cell CSV + BE1/BE2/BE3/BE4. Now re-run paper_final_breakeven_readoff.py.")


if __name__ == "__main__":
    main()
